# Generated by Django 5.1.6 on 2025-02-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_kor', models.CharField(max_length=50, null=True)),
                ('title_jap', models.CharField(max_length=50, null=True)),
                ('featuring', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_num', models.IntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='releases',
            field=models.ManyToManyField(related_name='releases', through='tracks.TrackNum', to='releases.release'),
        ),
    ]
