# Generated by Django 5.1.6 on 2025-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='featuring',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='title_jap',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='title_kor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
