# Generated by Django 5.1.6 on 2025-02-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupings', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grouping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='groupings.grouping')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='releases.releasegrouptype')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('annotation', models.TextField(max_length=200, null=True)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.country')),
                ('format_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='releases.releaseformat')),
                ('release_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.releasegroup')),
            ],
        ),
    ]
