# Generated by Django 5.1.6 on 2025-02-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupings', '0001_initial'),
        ('members', '0002_member_groupings_id_alter_member_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grouping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='groupings.groupings')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='releases.releasegrouptype')),
            ],
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('annotation', models.TextField(max_length=200)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.countries')),
                ('format_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='releases.releaseformats')),
                ('release_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.releasegroups')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_kor', models.CharField(max_length=50)),
                ('title_jap', models.CharField(max_length=50)),
                ('featuring', models.CharField(max_length=50)),
                ('releases', models.ManyToManyField(to='releases.releases')),
            ],
        ),
    ]
