# Generated by Django 5.1.6 on 2025-02-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0001_initial'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasegroup',
            name='grouping_id',
        ),
        migrations.AddField(
            model_name='releasegroup',
            name='groupings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupings_of_release_group', to='groupings.grouping'),
        ),
    ]
