# Generated by Django 5.1.6 on 2025-02-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_rename_format_id_release_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='country_id',
            new_name='country',
        ),
    ]
