# Generated by Django 5.1.6 on 2025-02-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0007_remove_releasegroup_groupings_releasegroup_grouping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasegroup',
            old_name='types',
            new_name='type',
        ),
    ]
