# Generated by Django 5.1.6 on 2025-02-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0008_rename_types_releasegroup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='annotation',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
