# Generated by Django 5.1.6 on 2025-02-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0009_alter_release_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='releases.releaseformat'),
        ),
    ]
