# Generated by Django 5.1.6 on 2025-02-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name_jap', models.CharField(max_length=30, null=True)),
                ('last_name_jap', models.CharField(max_length=30, null=True)),
                ('first_name_kor', models.CharField(max_length=30, null=True)),
                ('last_name_kor', models.CharField(max_length=30, null=True)),
                ('first_name_ch', models.CharField(max_length=30, null=True)),
                ('last_name_ch', models.CharField(max_length=30, null=True)),
                ('date_of_birth', models.CharField(max_length=10, null=True)),
                ('countries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.country')),
                ('groupings', models.ManyToManyField(related_name='groupings', to='groupings.grouping')),
            ],
        ),
    ]
