# Generated by Django 5.1.6 on 2025-02-13 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('first_name_jap', models.TextField(max_length=30)),
                ('last_name_jap', models.TextField(max_length=30)),
                ('first_name_kor', models.TextField(max_length=30)),
                ('last_name_kor', models.TextField(max_length=30)),
                ('first_name_ch', models.TextField(max_length=30)),
                ('last_name_ch', models.TextField(max_length=30)),
                ('date_of_birth', models.IntegerField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.countries')),
            ],
        ),
    ]
