# Generated by Django 5.1.6 on 2025-02-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='countries',
            new_name='country',
        ),
    ]
