# Generated by Django 5.1.6 on 2025-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='groupings_id',
            field=models.ManyToManyField(to='groupings.groupings'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name_ch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name_jap',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name_kor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name_ch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name_jap',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name_kor',
            field=models.CharField(max_length=30),
        ),
    ]
