# Generated by Django 5.1.6 on 2025-02-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_groupings_id_alter_member_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.CharField(max_length=10),
        ),
    ]
