# Generated by Django 5.1.6 on 2025-02-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0001_initial'),
        ('members', '0003_alter_member_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.countries'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name_ch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name_jap',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name_kor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='groupings_id',
            field=models.ManyToManyField(null=True, to='groupings.groupings'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name_ch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name_jap',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name_kor',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
